---

# Title: RHEL 7 to 8 upgrade playbook
# Author: Madhukar Beema

- hosts: all
  remote_user: mbeema
  become: yes
  serial: 4
  vars_files:
    - vars/rhel-vars.yml 
  roles:
    - role: register-subscription
    - role: rhel7-8upgrade
    - role: rhel7-8post